services:
  qnetd:
    container_name: proxmox-qdevice
    image: umm0n/proxmox-qdevice
    build: .
    ports:
      - "222:22"
      - "5403:5403"
    environment:
      - NEW_ROOT_PASSWORD={root_password}
    volumes:
      - /run/sshd
      - /volume1/docker/proxmox-qdevice/data:/etc/corosync
    restart: unless-stopped
    hostname: {homename}
    networks:
      qnetlan:
        ipv4_address: 172.18.1.10

networks:
  qnetlan:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "172.18.0.0/16"
